### PR TITLE
Data mal-form.

### PR DESCRIPTION
**Pull request by Nikolice**
To issues #65, #68, #71.

Pre-ambulae:
------------
I – was filling my **pro**-form, – not knowing that: many rows of «Contacts» (from «Home-page» – down-wards: «ICQ's U.I.N.», «Skype», …) – mis-matched lower labels, on my screen.

Result:
---------
Similar to #71 (a U.R.L. of the „FaceBook“ page = an „M.S.N.“ entity). 

Solution: 
============
By «Developer tools» (of a «Google: Chromium» installed) – I edited the C.S.S.:
* I – added a „clear: left;“ line – as a de-scription, for the «.form-group» class;
* I – know not: which – is better:
  * „clear: **left**;“ ?
  * „clear: **both**;“ ?
* Testing – is needed!

Conclusion:
------------
Rows (of «info» and «machine») – may be dis-played wrong, if:
* … on a big monitor (I – have a big one);
* … zoomed out. 

The data-base – should be re-vised: many people – may have mal-formed data.

### CODE REVIEW

**Comment by elbarbudo** [comment]
But now we get the problem on small screens :grinning: 
image

**Comment by Nikolice** [comment]
Well. I thought that: if I edit some files in the fork after the request (for pulling the fork in), -- then -- the request won't change. But it seems, that: if I edit the fork (which is requested for pulling in) -- then, the request contains all the changes -- even those, which were done after a request.

**Comment by christinloehner** [comment]
Thanks a lot! :-)

**Comment by Nikolice** [comment]
Not  done yet! See next re-quest: https://github.com/christinloehner/linuxcounter.new/pull/99

**Pull request merged**
