### PR TITLE
Data mal-form: wrong CSS-file.

### PR DESCRIPTION
**Pull request by Nikolice**
Continues the pull https://github.com/christinloehner/linuxcounter.new/pull/98.
To issues #65, #68, #71.

I see **no** changes to the forms now!

May be, the «custom.css» file – needs to be activated (by the frame-work of «Symfony-2») be-fore the usage – which will trans-form it in-to «validated.css». 

So, I re-moved the «clear: left» (of the «form-group» class): from «custom.css» – in-to the «validated.css».

### CODE REVIEW

**Comment by christinloehner** [comment]
@Nikolice  You are great! Thanks a lot for your work! Unfortunatly I have absolutely no time to do all this stuff by myself... so it is really great and I really highly appreciate it, that you try to fix some things!  Thanks a lot!  :-)

**Comment by Nikolice** [comment]
@christinloehner, thank you. Un-fortunately, I – do not know, how to test the engine (of the counter's service) as an installation on-to my own computer. But: I test it, as it works on your server. So, the changes I have pro-posed – were done through my «Developer tools» of «Google: Chromium» installation: on my computer, locally... I don't know, what to ask you about; but, you can try testing this pull request. As you can see – it has only two changes: a line, – moved from one file – to another. I do not know, how to force the frame-work (Symfony-2?) in-to doing it auto-matically; so, it can be done by merging the pull-request...

So.

Was the request merged? The GitHub – says: it was. But, still no changes. Though, in my "Chromium: DevTools" (if I re-do the "clear: left;" addition locally on my cache) – all seems fine.

But. https://www.linuxcounter.net/css/7be6bca.css – is the name of a CSS-file, where the data for CSS (used for ".form-data" { ... } ) currently lies, being located there by "Chromium: DevTools". It seems, to be created by the system, -- and is used, as a main CSS, which overrides every other CSS on a GitHub repository.

In order to make some real changes to the CSS of the site, – the system must be guided to another CSS-file, or – that file must be changed, to contain my commits.

**Comment by christinloehner** [comment]
Maybe I need to purge caches. I'll do this tomorrow morning (CEST)

**Comment by Nikolice** [comment]
Merged, closed; and – no changes.
The https://www.linuxcounter.net/css/7be6bca.css – still has no «clear: left;» for a «.form-group», according to my «Chromium: Dev.Tools»… So, either:
* The System – re-quires some time, for changes to be applied;
* The System – is waiting for an additional command: to re-build the CSS; (the variant, which I expect)
* The System – is fine, but I – re-ceive some cached data snap-shot, of the web-site.

I am in GMT+3. It is near a 23rd hour (mid-night) here…

**Comment by christinloehner** [comment]
@Nikolice  ...okay, there were some problems with the automated deployment process. Now everything works again as expected and also your "clear: left" now is in the validated.css file.

Further merges will work again.

**Comment by Nikolice** [comment]
Thank you!
I really see the change now.

**Pull request merged**
